/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: be186d94778e4953938b667b8d5cb6cd)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/workers/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
declare module "*.sh" {
	const value: string;
	export default value;
}