# TurboPanel filesystem layout (POSIX sh).
# Source after privileges.sh when needed.

TURBOPANEL_ROOT=/opt/turbopanel
TURBOPANEL_PLATFORM=$TURBOPANEL_ROOT/platform
TURBOPANEL_RUNTIMES_DIR=${TURBOPANEL_RUNTIMES_DIR:-$TURBOPANEL_ROOT/runtimes}
TURBOPANEL_RUNTIME=$TURBOPANEL_RUNTIMES_DIR

DENO_VERSION=2.8.3
DENO_RUNTIME_ROOT=$TURBOPANEL_RUNTIME/deno
DENO_VERSION_DIR=$DENO_RUNTIME_ROOT/$DENO_VERSION
DENO_BIN=$DENO_VERSION_DIR/deno
